# Generated by Django 5.2.7 on 2025-10-25 00:23

import volunteer_db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='event_date',
            field=models.DateField(validators=[volunteer_db.models.validate_future_date]),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='urgency',
            field=models.CharField(max_length=50, validators=[volunteer_db.models.validate_urgency]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='zipcode',
            field=models.CharField(max_length=10, validators=[volunteer_db.models.validate_zipcode]),
        ),
    ]