# Generated by Django 5.2.7 on 2025-10-28 03:52

import volunteer_db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_db', '0002_alter_eventdetails_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('XX', 'Unknown')], default='XX', max_length=2),
        ),
        migrations.RemoveField(
            model_name='eventdetails',
            name='event_date',
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='address',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='city',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='end_date',
            field=models.DateTimeField(default='2030-01-02T00:00:00Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='start_date',
            field=models.DateTimeField(default='2030-01-01T00:00:00Z', validators=[volunteer_db.models.validate_future_date]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='state',
            field=models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('XX', 'Unknown')], default='XX', max_length=2),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='zip_code',
            field=models.CharField(default='', max_length=10, validators=[volunteer_db.models.validate_zipcode]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='required_skills',
            field=models.JSONField(null=True, validators=[volunteer_db.models.validate_is_list]),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='urgency',
            field=models.CharField(max_length=50, null=True, validators=[volunteer_db.models.validate_urgency]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.JSONField(null=True, validators=[volunteer_db.models.validate_is_list]),
        ),
        migrations.DeleteModel(
            name='States',
        ),
    ]
