# Generated by Django 5.2.7 on 2025-10-30 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_db', '0002_alter_eventdetails_event_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventdetails',
            options={'verbose_name': 'Event Detail', 'verbose_name_plural': 'Event Details'},
        ),
        migrations.AlterModelOptions(
            name='states',
            options={'verbose_name': 'State', 'verbose_name_plural': 'States'},
        ),
        migrations.AlterModelOptions(
            name='usercredentials',
            options={'verbose_name': 'User Credential', 'verbose_name_plural': 'User Credentials'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterModelOptions(
            name='volunteerhistory',
            options={'verbose_name': 'Volunteer History', 'verbose_name_plural': 'Volunteer Histories'},
        ),
    ]
