# Generated by Django 5.2.7 on 2025-10-31 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_db', '0003_alter_userprofile_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerhistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
