# Generated by Django 5.2.7 on 2025-10-31 20:49

import volunteer_db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_db', '0004_volunteerhistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='urgency',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[volunteer_db.models.validate_urgency]),
        ),
    ]
