# Generated by Django 5.2.7 on 2025-11-09 03:43

import volunteer_db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_db', '0005_alter_eventdetails_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='urgency',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[volunteer_db.models.validate_urgency]),
        ),
    ]
