# Generated by Django 5.2.7 on 2025-11-21 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_db', '0006_alter_eventdetails_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerhistory',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='volunteer_db.userprofile'),
            preserve_default=False,
        ),
    ]
