# Generated by Django 5.2.7 on 2025-11-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_db', '0006_alter_eventdetails_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='availability_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
