# Generated by Django 5.2.7 on 2025-11-22 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_db', '0007_userprofile_availability_json'),
        ('volunteer_db', '0007_volunteerhistory_user_profile'),
    ]

    operations = [
    ]
