# Generated by Django 5.2.7 on 2025-11-23 23:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_db', '0008_merge_20251121_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerhistory',
            name='match_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='volunteerhistory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
