# Generated by Django 5.2.7 on 2025-11-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_db', '0008_merge_20251121_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercredentials',
            name='username',
        ),
        migrations.AlterField(
            model_name='usercredentials',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
