# Generated by Django 5.2.7 on 2025-11-25 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_db', '0009_volunteerhistory_match_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer_db.userprofile'),
        ),
    ]
