# Generated by Django 5.2.7 on 2025-11-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_db', '0010_alter_notification_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerhistory',
            name='match_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automatic')], default='auto', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='volunteerhistory',
            unique_together={('user', 'event', 'participation_date')},
        ),
    ]
