# Generated by Django 5.2.7 on 2025-11-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_db', '0011_alter_volunteerhistory_match_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredentials',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='usercredentials',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
